name: Build and Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - development
          - production
        default: production
      port:
        description: 'Enter the port number'
        required: true
        type: string
        default: '3000'

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, feature]
    env:
      MY_VARIABLE: ${{ matrix.branch == 'main' && 'main-branch-value' || 'feature-branch-value' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run job for develop branch
        run: echo "This job runs only on the ${MY_VARIABLE}."
  
    
