name: Build and Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - development
          - production
        default: production
      port:
        description: 'Enter the port number'
        required: true
        type: string
        default: '3000'

jobs:
  job-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run job for main branch
        run: echo "This job runs only on the main branch."

  job-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run job for develop branch
        run: echo "This job runs only on the develop branch."
