name: Build and Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - development
          - production
        default: production
      port:
        description: 'Enter the port number'
        required: true
        type: string
        default: '3000'

jobs:
  zip-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip of folder a
        working-directory: ./A
        run: |
          zip -r ../archive.zip .

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: folder-a-zip
          path: folder_a.zip
